import{a as i,C as p,i as l}from"./assets/vendor-55bcc3c7.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();i.defaults.headers.common["x-api-key"]="live_nOdnL3Dj9jjF4zVLjteozldoqmiVUxxCRsrlPoRVyonLQDm4DFuaUNiaRzafsnXC";async function m(){return i.get("https://api.thecatapi.com/v1/breeds")}async function u(r){return i.get("https://api.thecatapi.com/v1/images/search?",{params:{breed_ids:r}})}const s={loader:document.querySelector(".loader"),catInfo:document.querySelector(".cat-info"),select:document.querySelector(".breed-select")},d={class:"promisesToast",position:"topRight",close:!1,timeout:3e3};m().then(r=>{s.select.classList.remove("hide");const o=r.data.map(({id:n,name:a})=>`
    <option value=${n}>${a}</option>
  `).join("");s.select.insertAdjacentHTML("afterbegin",o),new p(s.select,{searchEnabled:!0})}).catch(()=>{l.error({message:"❌ Oops! Something went wrong! Try reloading the page!",...d})}).finally(()=>{s.loader.classList.add("hide")});s.select.addEventListener("change",f);function f(){s.catInfo.classList.add("hide"),s.loader.classList.remove("hide"),u(s.select.value).then(r=>{const[{url:o,breeds:[{name:n,description:a,temperament:e}]}]=r.data,t=`
        <img src="${o}" alt="${n}">
        <div class="cat-info-text">
        <h2>${n}</h2>
        <p>${a}</p>
        <p><span>Temperament</span>: ${e}</p>
        </div>
        `;s.catInfo.innerHTML=t}).catch(()=>{l.error({message:"❌ Oops! Something went wrong! Try reloading the page!",...d})}).finally(()=>{s.catInfo.classList.remove("hide"),s.loader.classList.add("hide")})}
//# sourceMappingURL=commonHelpers.js.map
